default:
  image: crystallang/crystal:latest-alpine
  before_script:
    - apk add --no-cache make git libsodium-dev tpm2-tss-dev pcre2-dev yaml-dev yaml-static
  interruptible: true

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - make lint
    - make test

pages:
  stage: deploy
  script:
    - make docs
    - mkdir -p public
    - cp -r docs/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
