default:
  image: crystallang/crystal:latest
  before_script:
    - apt-get update -qq && apt-get install -y -qq --no-install-recommends make git libsodium-dev libtss2-dev libpcre2-dev >/dev/null 2>&1
  interruptible: true

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - shards install
    - make lint
    - make test

pages:
  stage: deploy
  script:
    - make docs
    - mkdir -p public
    - cp -r docs/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
